[window]
startup_mode = "Maximized"

[terminal]
shell = "/bin/zsh"

[font]
size = 12.0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]
